baseURL = "https://ajm188.github.io"
languageCode = "en-us"
title = "Home"
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
  [markup.highlight]
  codeFences=true
  guessSyntax=false
  hl_Lines=""
  lineNoStart=1
  lineNos=true
  lineNumbersInTable=true
  noClasses=true
  ## Good alternatives include:
  # - fruity (eh)
  # - monokai
  # - native
  # - solarized-dark(256)? but they conflict with inline code style
  style="dracula"
