baseURL = "https://a.ndrw.dev"
languageCode = "en-us"
title = "Home"
disableKinds = ["taxonomy", "taxonomyTerm"]

[outputFormats]
  [outputFormats.txt]
    isPlainText = true
    notAlternative = true
    mediaType = "text/plain"

[markup]
  [markup.highlight]
  codeFences=true
  guessSyntax=false
  hl_Lines=""
  lineNoStart=1
  lineNos=true
  lineNumbersInTable=true
  noClasses=true
  ## Good alternatives include:
  # - fruity (eh)
  # - monokai
  # - native
  # - solarized-dark(256)? but they conflict with inline code style
  style="dracula"
